/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fb',
        'outline-variant': '#c4c5d9',
        'on-background': '#191c1e',
        tertiary: '#00623d',
        'surface-tint': '#104af0',
        secondary: '#7b24dc',
        'secondary-container': '#9547f7',
        primary: '#0040df',
        'on-tertiary-fixed-variant': '#005232',
        background: '#f7f9fb',
        'on-tertiary-fixed': '#002111',
        'on-primary-fixed': '#001355',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'primary-fixed-dim': '#b8c3ff',
        'surface-dim': '#d8dadc',
        'on-error-container': '#93000a',
        'on-primary-container': '#efefff',
        'primary-fixed': '#dde1ff',
        'tertiary-container': '#007d4f',
        'on-surface-variant': '#434656',
        'primary-container': '#2d5bff',
        'error-container': '#ffdad6',
        outline: '#747688',
        'surface-container': '#eceef0',
        'surface-bright': '#f7f9fb',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'tertiary-fixed': '#50ffaf',
        'on-secondary-container': '#fffbff',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#d8b9ff',
        'surface-container-low': '#f2f4f6',
        'inverse-on-surface': '#eff1f3',
        'tertiary-fixed-dim': '#00e293',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#bcffd5',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#0035bd',
        'on-secondary-fixed-variant': '#6200bc',
        'inverse-primary': '#b8c3ff',
        'on-secondary-fixed': '#290055',
        'on-primary': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e0e3e5',
        'secondary-fixed': '#eddcff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '16px',
        'card-gap': '20px',
        gutter: '24px',
        'container-padding': '32px',
        xxl: '48px',
        lg: '24px',
        xxs: '4px',
        sm: '12px',
        md: '16px',
        xl: '32px',
        xs: '8px',
      },
      fontFamily: {
        'headline-lg': ['Poppins'],
        'label-bold': ['Poppins'],
        'body-md': ['Poppins'],
        'display-lg': ['Poppins'],
        'headline-md': ['Poppins'],
        'headline-lg-mobile': ['Poppins'],
        'body-lg': ['Poppins'],
        'label-sm': ['Poppins'],
        'label-md': ['Poppins'],
      },
      fontSize: {
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
